// Sample texts for different levels
export const textSamples = {
    easy: [
      `The sun was shining brightly as Emma walked to the park with her little dog, Charlie. Birds chirped in the trees, and children laughed as they played on the swings. Emma sat on a bench, watching the world around her. Charlie barked happily as he chased a butterfly. A little boy ran up to pet him, and Charlie wagged his tail in delight. The boy’s mother smiled and thanked Emma for letting her son play with Charlie. As the day turned to evening, Emma and Charlie walked home, feeling peaceful and happy after their lovely day..`,
      `Every Saturday, Sarah visited her grandmother’s house. The smell of fresh cookies greeted her at the door. Grandma always had a new recipe to try, and Sarah loved helping her bake. Today, they were making chocolate chip cookies. Sarah mixed the dough while Grandma added the chocolate chips. They laughed as flour spilled onto the counter. After baking, the kitchen filled with a sweet, warm aroma. They sat at the table, enjoying their cookies with a glass of milk. Sarah thought there was nothing better than time spent in Grandma’s kitchen.`,
      `While walking home from school, Mia heard a faint meowing sound. She looked around and saw a small kitten stuck in a bush. Carefully, Mia reached in and gently pulled the kitten out. Its fur was soft but dirty, and it looked up at her with wide, curious eyes. Mia decided to take the kitten home and care for it. She gave it a warm bath, a bowl of milk, and a cozy blanket to sleep on. The next day, Mia’s family decided to adopt the kitten. They named it Whiskers, and it became a beloved member of their family.`,
      `Liam and his friends loved exploring the woods near their neighborhood. One sunny afternoon, they decided to search for hidden treasures. Armed with a map and a flashlight, they followed a trail that led to a small cave. Inside, they found shiny rocks, colorful feathers, and even an old coin. Excited by their discoveries, they imagined themselves as brave explorers on a great adventure. As the sun began to set, they returned home, promising to come back another day. The woods were full of mysteries, and they couldn’t wait to see what they would find next.`,
      `It was a gloomy, rainy day, and Lucas felt bored sitting inside. He stared out the window, watching raindrops race down the glass. Then, he had an idea. He grabbed some paper, crayons, and glue from his art box and started creating. Lucas made a colorful collage of a sunny beach with palm trees and a bright blue sky. His mom walked in and smiled at his masterpiece. “It looks like summer,” she said. Lucas felt proud. Even though the rain continued outside, his artwork brought a little sunshine to their home.`,
      `One day, Emma found a strange box in her attic. Inside was a small robot with a button on its chest. Curious, she pressed the button, and the robot came to life. “Hello!” it said in a cheerful voice. Emma named it Max and discovered that it could do all sorts of things, like clean her room, help with homework, and even tell jokes. Max quickly became her best friend. They spent hours playing games and learning new things. Emma felt lucky to have such a special friend, and Max was happy to be part of her life.`
    ],
    medium: [
      `Sophie loved puzzles and mysteries. One rainy afternoon, while exploring her grandmother's old attic, she discovered a small wooden box with intricate carvings. The box was locked, and there was no sign of the key. Determined to uncover its secret, Sophie searched every corner of the attic. Under an old rocking chair, she found a dusty envelope with a note inside. It read, "The key lies where memories are kept." She rushed to her grandmother’s photo album shelf and found the key taped to the back of an old family portrait. Excitedly, she unlocked the box, revealing a collection of love letters from her grandparents' early days. It was a treasure far greater than she had imagined.`,
      `The bustling market was alive with vibrant colors and tantalizing aromas. Vendors called out, advertising their fresh produce, handmade crafts, and spices from distant lands. Olivia wandered through the rows of stalls, marveling at the variety. She sampled a slice of juicy mango from a friendly fruit seller and bought a small jar of golden honey. A musician played a cheerful tune on his guitar, drawing a small crowd. Olivia stopped to listen, her arms full of treasures she had collected. As the sun began to set, the market lights twinkled, creating a magical atmosphere she wouldn’t soon forget.`,
      `On the edge of a rocky cliff stood an old lighthouse, its beacon guiding ships to safety. For decades, Mr. Hargrove had been the keeper of the light. Many in the nearby village speculated about his solitary life. One stormy night, a young fisherman named Caleb sought shelter at the lighthouse. Inside, he noticed rows of shelves lined with jars, each containing a message written on a small piece of paper. Mr. Hargrove explained that they were notes left by sailors who had survived treacherous storms thanks to the lighthouse. Each jar held a story of gratitude and hope, a legacy that Mr. Hargrove quietly preserved.`,
      `It was a snowy evening, and the fireplace crackled warmly in Emma’s living room. She was curled up with a book when she heard a soft knock at the door. Surprised, she opened it to find a young woman shivering on the porch, clutching a suitcase. “My car broke down,” the woman explained. Emma invited her inside, offering a blanket and a cup of tea. Over the next hour, they talked and laughed, discovering they had many interests in common. By the time the tow truck arrived, they had exchanged phone numbers. What began as an unexpected visit turned into the start of a lasting friendship.`,
      `Deep in the heart of the forest, there was a garden known only to a few. It wasn’t an ordinary garden; each plant seemed to glow faintly, as though lit from within. One day, a curious boy named Leo stumbled upon the garden while chasing a butterfly. As he entered, he felt a strange sense of calm and wonder. An elderly woman appeared, introducing herself as the caretaker. She explained that the garden was nourished by kindness and good deeds. Each glowing flower represented an act of love or generosity. Inspired, Leo vowed to be kinder and returned often to see the garden grow brighter.`,
      `In a quaint village, there lived a clockmaker named Mr. Alden, known for his intricate and precise creations. He took on an apprentice, a young girl named Clara, who was fascinated by the inner workings of clocks. Mr. Alden taught her how to carefully align gears, adjust springs, and polish the delicate hands of timepieces. One day, Clara discovered a broken pocket watch that belonged to Mr. Alden’s late wife. Determined to fix it, she worked tirelessly, using every skill she had learned. When she presented the restored watch to Mr. Alden, he was moved to tears. Clara’s dedication had not only repaired the watch but also brought back cherished memories.`
    ],
    hard: [
      `In the dusty corner of an old library, hidden beneath stacks of forgotten books, lay a tattered manuscript bound in faded leather. It had been overlooked for generations, its contents fading from memory. When Professor Hawthorne stumbled upon it, he was immediately struck by the elegance of the handwriting and the peculiar symbols scattered throughout the pages. The manuscript detailed a forgotten civilization, one whose knowledge had been lost to time. As Hawthorne painstakingly deciphered the ancient text, he discovered a map that led to a hidden city, said to be the final resting place of a powerful artifact. The scholar’s obsession with unlocking its secrets would take him on an adventure beyond anything he could have imagined.`,
      `In the quiet study of a distinguished philosopher, a heated debate raged within the pages of an unfinished manuscript. For years, Dr. Marcus Vale had grappled with the concept of time, attempting to unravel the paradoxes that had confounded the greatest minds for centuries. His theory, which posited that time was not linear but cyclical, challenged everything that had been previously understood. As he sifted through ancient texts and modern scientific theories, a troubling question arose: If time could be altered, could one truly change the past? Vale’s obsession with this paradox led him down a path where the boundaries between theory and reality began to blur, and he found himself questioning the very fabric of existence.`,
      `Beneath the vast expanse of the ocean lies a world teeming with life, much of it still undiscovered by humankind. Dr. Elena Grayson had spent her life studying the deep sea, but even she was unprepared for the revelations of her latest expedition. As her research submarine descended into the abyss, she encountered strange, bioluminescent creatures that defied conventional understanding of marine biology. But it wasn’t just the lifeforms that intrigued her—it was the strange, almost otherworldly structures that seemed to rise from the ocean floor, untouched by time. As Dr. Grayson and her crew explored these submerged ruins, they uncovered evidence of an ancient civilization, one that had thrived long before any known human societies. The implications of their discovery would alter the course of history forever.`,
      `Detective Adrian Blackwood had solved countless cases during his career, but the murder of a prominent politician left him with more questions than answers. The crime scene was eerily devoid of clues. No fingerprints, no sign of forced entry, and no witnesses—except for a single, cryptic note left beside the body. The note, written in an ancient cipher, seemed to mock Blackwood’s every move. As he decoded the message, it led him to a shadowy group with ties to some of the world’s most powerful individuals. The deeper Blackwood delved into the case, the more he realized he was no longer just investigating a murder—he was uncovering a conspiracy that reached into the highest echelons of society, and his own life was now at risk.`,
      `Captain Edmund Roark had sailed the seven seas for over forty years, but his final voyage would take him to the edge of the known world. The maps he possessed were centuries old, marked with strange symbols and cryptic warnings. Legend spoke of an island that vanished from sight, a place that could only be reached by those who dared to challenge the boundaries of time and space. As Roark's ship, The Tempest, sailed farther into uncharted waters, the crew began to experience strange occurrences. They saw islands that didn’t exist, heard voices carried by the wind, and found their navigation instruments malfunctioning. Soon, Roark realized that their journey had taken them beyond the physical world into a realm where reality itself was distorted. The island, if it existed at all, was a place where the laws of nature no longer applied.`,
      `In a city where towering skyscrapers stretched toward the heavens, one architect stood out above the rest. Lucien Devereux was a visionary, a man whose designs defied gravity and logic. His latest project, a building that seemed to fold in on itself like a twisted labyrinth, promised to be his greatest achievement. But as construction began, strange things started to happen. Workers reported feeling disoriented, as if the very structure of the building was warping their perceptions of space. Some claimed they had glimpsed glimpses of alternate realities—visions of an entirely different city, one that mirrored their own but existed in another dimension. As the building neared completion, Devereux became obsessed with the idea that his creation had unlocked a doorway to another world, and he was determined to cross it, no matter the cost.`
    ]
  };

  export function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
}